#!/bin/bash
# Mock script for development - lists authenticated clients
echo "=Ë [DEV] Authenticated clients:"
echo "  aa-bb-cc-dd-ee-ff (192.168.100.10) - Test Device 1"
echo "  11-22-33-44-55-66 (192.168.100.11) - Test Device 2"
# In production, this would query iptables
# iptables -t nat -L CAPTIVE_PORTAL -n | grep "MAC" | awk '{print $7}' | sort | uniq